title: CharlesAnHalJulige
email: kingsj0405@naver.com
description: EWOOSOFT Study Group
baseurl:
url: 'https://charlesanhaljulige.github.io/'
github_username: CharlesAnHalJulige
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
